// Kullanici istegi: test kontrol listesindeki 54 senaryo - ilk
// kurulumda (tablo bossa) tohumlanir.
export const DEFAULT_TEST_CASES: {
  no: number;
  section: string;
  scenario: string;
  expectedResult: string;
}[] = [
  { no: 1, section: "Giris / Kimlik Dogrulama", scenario: "Yeni bir telefon numarasiyla OTP kodu isteme", expectedResult: "Kod SMS ile gonderilir, hata vermez" },
  { no: 2, section: "Giris / Kimlik Dogrulama", scenario: "Telefon alani otomatik doldurulmuyor mu (mobil)", expectedResult: "Alan bos baslar, titremeden yazilabilir" },
  { no: 3, section: "Giris / Kimlik Dogrulama", scenario: "Dogru kod ile giris", expectedResult: "Basariyla giris yapilir" },
  { no: 4, section: "Giris / Kimlik Dogrulama", scenario: "Yanlis kod ile giris", expectedResult: "Net bir hata mesaji gosterilir" },
  { no: 5, section: "Giris / Kimlik Dogrulama", scenario: "Giris sonrasi yonlendirme", expectedResult: "Her zaman /panel sayfasina dusulur" },
  { no: 6, section: "Panel (Ana Sayfa)", scenario: "Karsilama mesaji", expectedResult: "Isim varsa 'Merhaba, [Isim]!' gorunur" },
  { no: 7, section: "Panel (Ana Sayfa)", scenario: "En cok iletisim kurduklarin bolumu", expectedResult: "En aktif 3 konusma, mesaj sayisina gore sirali gorunur" },
  { no: 8, section: "Panel (Ana Sayfa)", scenario: "Ilgini cekebilecekler bolumu", expectedResult: "Kategoriye gore onerilen sorular gorunur" },
  { no: 9, section: "Panel (Ana Sayfa)", scenario: "Hizli eylem butonlari", expectedResult: "Mesaj Gonder / Havuza Goz At dogru sayfaya gider" },
  { no: 10, section: "Panel (Ana Sayfa)", scenario: "Logo linki (baglama gore)", expectedResult: "Panel'deyken ana sayfaya, baska yerdeyken Panel'e gider" },
  { no: 11, section: "Mesaj Gonderme", scenario: "Yeni mesaj olusturma", expectedResult: "Telefon + mesaj + kilit tipi ile basariyla gonderilir" },
  { no: 12, section: "Mesaj Gonderme", scenario: "Rehberden numara secimi", expectedResult: "Numara ve ulke kodu dogru dolar" },
  { no: 13, section: "Mesaj Gonderme", scenario: "Mesaj Onerileri listesi", expectedResult: "Acilir, secilince metne yazilir" },
  { no: 14, section: "Mesaj Gonderme", scenario: "Okununca Sil / Hava Durumu secenekleri", expectedResult: "Gri metin, aralarinda net bosluk var" },
  { no: 15, section: "Mesaj Gonderme", scenario: "Anonim/acik avatar tercihi", expectedResult: "Ayarlardaki tercihe gore dogru gonderilir" },
  { no: 16, section: "Konusma Ekrani", scenario: "Mesajlar arasi tarih ayirici", expectedResult: "Bugun / gun adi / tam tarih dogru gosterilir" },
  { no: 17, section: "Konusma Ekrani", scenario: "Yanitla (oneri popup)", expectedResult: "Karsi tarafin mesaji altinda acilir ve calisir" },
  { no: 18, section: "Konusma Ekrani", scenario: "Tepki (emoji) verme", expectedResult: "Tepki eklenir/kaldirilir" },
  { no: 19, section: "Konusma Ekrani", scenario: "Yanit formu secenekleri", expectedResult: "Hava durumu / okununca sil calisir" },
  { no: 20, section: "Konusma Ekrani", scenario: "Kisiyi blokla/bloktan cikar", expectedResult: "Islem basariyla gerceklesir" },
  { no: 21, section: "Guardrail (Toksisite Sistemi)", scenario: "Toksik mesaj gonderimi", expectedResult: "Inceleme bildirimi gelir, karsi tarafa ulasmaz" },
  { no: 22, section: "Guardrail (Toksisite Sistemi)", scenario: "Admin ekraninda inceleme listesi", expectedResult: "Mesaj Incelemedeki Mesajlar'da gorunur" },
  { no: 23, section: "Guardrail (Toksisite Sistemi)", scenario: "Sorun Yok onayi", expectedResult: "Mesaj iletilir, blok kalkar" },
  { no: 24, section: "Guardrail (Toksisite Sistemi)", scenario: "Sorun Var onayi (ihlal)", expectedResult: "X gun blok + bildirim dogru gelir" },
  { no: 25, section: "Guardrail (Toksisite Sistemi)", scenario: "ihlal", expectedResult: "Y gun blok + 'tekrari halinde suresiz' uyarisi gelir" },
  { no: 26, section: "Guardrail (Toksisite Sistemi)", scenario: "ihlal", expectedResult: "Suresiz blok uygulanir" },
  { no: 27, section: "Guardrail (Toksisite Sistemi)", scenario: "Inceleme altindaki kisiler listesi", expectedResult: "Ihlal sayisi gorunur, Incelemeden Cikar calisir" },
  { no: 28, section: "Guardrail (Toksisite Sistemi)", scenario: "Toksik kelime listesi yonetimi", expectedResult: "Ekleme/duzenleme/silme calisir" },
  { no: 29, section: "Guardrail (Toksisite Sistemi)", scenario: "Sureli blogun otomatik kalkmasi", expectedResult: "Sure dolunca otomatik kalkar, bildirim gelir" },
  { no: 30, section: "Blok Sistemi", scenario: "Manuel blokla/kaldir", expectedResult: "Islem basariyla gerceklesir" },
  { no: 31, section: "Blok Sistemi", scenario: "Bloklu kisiye mesaj gonderme denemesi", expectedResult: "Sistem/kisi ayrimi net bir hata mesaji gosterilir" },
  { no: 32, section: "Blok Sistemi", scenario: "Tum Bloklar listesi (admin)", expectedResult: "Guncel ve dogru gorunur" },
  { no: 33, section: "Blok Sistemi", scenario: "Blok Gecmisi (admin)", expectedResult: "Gecmis kayitlar kalici, cikis tarihleri dogru" },
  { no: 34, section: "Blok Sistemi", scenario: "Blok Gecmisi arama filtresi", expectedResult: "Telefon/isim ile filtreleme calisir" },
  { no: 35, section: "Blok Sistemi", scenario: "Tekrarli blok kayitlari", expectedResult: "Her tekrarda yeni kayit + kumulatif sayi artar" },
  { no: 36, section: "Rehber", scenario: "Otomatik kisi ekleme", expectedResult: "Mesaj gonderilen numara rehbere eklenir" },
  { no: 37, section: "Rehber", scenario: "Karsi taraftan avatar/isim guncelleme", expectedResult: "Anonim degilse yanit sonrasi rehbere eklenir" },
  { no: 38, section: "Rehber", scenario: "Manuel kisi ekleme/duzenleme/silme", expectedResult: "Islemler basariyla gerceklesir" },
  { no: 39, section: "Rehber", scenario: "Rehberden Sec (mesaj olustururken)", expectedResult: "Arama + not gosterimiyle calisir" },
  { no: 40, section: "Havuz (Pool)", scenario: "Yeni soru olusturma", expectedResult: "Basariyla olusturulur" },
  { no: 41, section: "Havuz (Pool)", scenario: "Liste sayfasi formati", expectedResult: "Sorular tabular/kompakt formatta gorunur" },
  { no: 42, section: "Havuz (Pool)", scenario: "Listeden dogrudan tepki verme", expectedResult: "Detaya girmeden tepki verilebilir" },
  { no: 43, section: "Havuz (Pool)", scenario: "Soruya yanit verme/kabul-red", expectedResult: "Islemler basariyla gerceklesir" },
  { no: 44, section: "Havuz (Pool)", scenario: "Kategoriye gore filtreleme", expectedResult: "Dogru sonuclari gosterir" },
  { no: 45, section: "Ayarlar", scenario: "Avatar/nickname gorunurlugu", expectedResult: "Tercih degisikligi calisir" },
  { no: 46, section: "Ayarlar", scenario: "Genel blok ac/kapa", expectedResult: "Tercih degisikligi calisir" },
  { no: 47, section: "Ayarlar", scenario: "Bloklanan Mesajlar listesi", expectedResult: "Goruntuleme ve Kaldir butonu calisir" },
  { no: 48, section: "Ayarlar", scenario: "Tum mesajlari sil / hesabi sil", expectedResult: "Islem calisir (DIKKATLI test edilmeli)" },
  { no: 49, section: "Admin Ekranlari", scenario: "Admin ana panel kartlari", expectedResult: "Tum kartlar dogru sayfaya linklenir" },
  { no: 50, section: "Admin Ekranlari", scenario: "Mesaj Onerileri yonetimi", expectedResult: "Ekleme (tekli/coklu)/duzenleme/silme calisir" },
  { no: 51, section: "Admin Ekranlari", scenario: "Sikayetler / Gunlukler / Ayarlar", expectedResult: "Erisilebilir ve islevsel" },
  { no: 52, section: "Genel / Performans", scenario: "Mesajlarim listesi hizi", expectedResult: "Hizli aciliyor" },
  { no: 53, section: "Genel / Performans", scenario: "Ingilizce dil degisikligi", expectedResult: "Yeni eklenen metinler de cevrilmis" },
  { no: 54, section: "Genel / Performans", scenario: "Mobil temel akislar", expectedResult: "Giris/mesaj gonderme/okuma sorunsuz" },
];
