// Dunyadaki tum ulkeler icin telefon kodu listesi (ISO-3166 alpha-2 +
// uluslararasi arama kodu). Bayrak emoji'leri kodu uzerinden otomatik
// uretiliyor. Liste, gosterim sirasinda Turkce isme gore alfabetik
// olarak siralanir (bkz. COUNTRIES export'u).
export interface CountryOption {
  iso2: string;
  name: string;
  dialCode: string; // "+" isareti olmadan, orn. "90"
}

const RAW_COUNTRIES: CountryOption[] = [
  { iso2: "AF", name: "Afganistan", dialCode: "93" },
  { iso2: "ZA", name: "Güney Afrika", dialCode: "27" },
  { iso2: "AL", name: "Arnavutluk", dialCode: "355" },
  { iso2: "DZ", name: "Cezayir", dialCode: "213" },
  { iso2: "DE", name: "Almanya", dialCode: "49" },
  { iso2: "AD", name: "Andorra", dialCode: "376" },
  { iso2: "AO", name: "Angola", dialCode: "244" },
  { iso2: "AG", name: "Antigua ve Barbuda", dialCode: "1268" },
  { iso2: "AR", name: "Arjantin", dialCode: "54" },
  { iso2: "AM", name: "Ermenistan", dialCode: "374" },
  { iso2: "AU", name: "Avustralya", dialCode: "61" },
  { iso2: "AT", name: "Avusturya", dialCode: "43" },
  { iso2: "AZ", name: "Azerbaycan", dialCode: "994" },
  { iso2: "BS", name: "Bahamalar", dialCode: "1242" },
  { iso2: "BH", name: "Bahreyn", dialCode: "973" },
  { iso2: "BD", name: "Bangladeş", dialCode: "880" },
  { iso2: "BB", name: "Barbados", dialCode: "1246" },
  { iso2: "BE", name: "Belçika", dialCode: "32" },
  { iso2: "BZ", name: "Belize", dialCode: "501" },
  { iso2: "BJ", name: "Benin", dialCode: "229" },
  { iso2: "BY", name: "Belarus", dialCode: "375" },
  { iso2: "BT", name: "Butan", dialCode: "975" },
  { iso2: "BO", name: "Bolivya", dialCode: "591" },
  { iso2: "BA", name: "Bosna Hersek", dialCode: "387" },
  { iso2: "BW", name: "Botsvana", dialCode: "267" },
  { iso2: "BR", name: "Brezilya", dialCode: "55" },
  { iso2: "BN", name: "Brunei", dialCode: "673" },
  { iso2: "BG", name: "Bulgaristan", dialCode: "359" },
  { iso2: "BF", name: "Burkina Faso", dialCode: "226" },
  { iso2: "BI", name: "Burundi", dialCode: "257" },
  { iso2: "TD", name: "Çad", dialCode: "235" },
  { iso2: "CZ", name: "Çekya", dialCode: "420" },
  { iso2: "CN", name: "Çin", dialCode: "86" },
  { iso2: "DJ", name: "Cibuti", dialCode: "253" },
  { iso2: "DM", name: "Dominika", dialCode: "1767" },
  { iso2: "DO", name: "Dominik Cumhuriyeti", dialCode: "1809" },
  { iso2: "DK", name: "Danimarka", dialCode: "45" },
  { iso2: "TL", name: "Doğu Timor", dialCode: "670" },
  { iso2: "EC", name: "Ekvador", dialCode: "593" },
  { iso2: "GQ", name: "Ekvator Ginesi", dialCode: "240" },
  { iso2: "SV", name: "El Salvador", dialCode: "503" },
  { iso2: "ID", name: "Endonezya", dialCode: "62" },
  { iso2: "ER", name: "Eritre", dialCode: "291" },
  { iso2: "EE", name: "Estonya", dialCode: "372" },
  { iso2: "ET", name: "Etiyopya", dialCode: "251" },
  { iso2: "FJ", name: "Fiji", dialCode: "679" },
  { iso2: "PH", name: "Filipinler", dialCode: "63" },
  { iso2: "PS", name: "Filistin", dialCode: "970" },
  { iso2: "FI", name: "Finlandiya", dialCode: "358" },
  { iso2: "FR", name: "Fransa", dialCode: "33" },
  { iso2: "GA", name: "Gabon", dialCode: "241" },
  { iso2: "GM", name: "Gambiya", dialCode: "220" },
  { iso2: "GH", name: "Gana", dialCode: "233" },
  { iso2: "GE", name: "Gürcistan", dialCode: "995" },
  { iso2: "GD", name: "Grenada", dialCode: "1473" },
  { iso2: "GT", name: "Guatemala", dialCode: "502" },
  { iso2: "GN", name: "Gine", dialCode: "224" },
  { iso2: "GW", name: "Gine-Bissau", dialCode: "245" },
  { iso2: "GY", name: "Guyana", dialCode: "592" },
  { iso2: "ZM", name: "Zambiya", dialCode: "260" },
  { iso2: "HT", name: "Haiti", dialCode: "509" },
  { iso2: "IN", name: "Hindistan", dialCode: "91" },
  { iso2: "NL", name: "Hollanda", dialCode: "31" },
  { iso2: "HN", name: "Honduras", dialCode: "504" },
  { iso2: "HR", name: "Hırvatistan", dialCode: "385" },
  { iso2: "IQ", name: "Irak", dialCode: "964" },
  { iso2: "IR", name: "İran", dialCode: "98" },
  { iso2: "IE", name: "İrlanda", dialCode: "353" },
  { iso2: "ES", name: "İspanya", dialCode: "34" },
  { iso2: "IL", name: "İsrail", dialCode: "972" },
  { iso2: "SE", name: "İsveç", dialCode: "46" },
  { iso2: "CH", name: "İsviçre", dialCode: "41" },
  { iso2: "IT", name: "İtalya", dialCode: "39" },
  { iso2: "IS", name: "İzlanda", dialCode: "354" },
  { iso2: "JM", name: "Jamaika", dialCode: "1876" },
  { iso2: "JP", name: "Japonya", dialCode: "81" },
  { iso2: "KH", name: "Kamboçya", dialCode: "855" },
  { iso2: "CM", name: "Kamerun", dialCode: "237" },
  { iso2: "CA", name: "Kanada", dialCode: "1" },
  { iso2: "ME", name: "Karadağ", dialCode: "382" },
  { iso2: "QA", name: "Katar", dialCode: "974" },
  { iso2: "KZ", name: "Kazakistan", dialCode: "7" },
  { iso2: "KE", name: "Kenya", dialCode: "254" },
  { iso2: "CY", name: "Kıbrıs", dialCode: "357" },
  { iso2: "KG", name: "Kırgızistan", dialCode: "996" },
  { iso2: "KI", name: "Kiribati", dialCode: "686" },
  { iso2: "CO", name: "Kolombiya", dialCode: "57" },
  { iso2: "KM", name: "Komorlar", dialCode: "269" },
  { iso2: "CG", name: "Kongo", dialCode: "242" },
  { iso2: "CD", name: "Kongo Demokratik Cumhuriyeti", dialCode: "243" },
  { iso2: "KR", name: "Güney Kore", dialCode: "82" },
  { iso2: "KP", name: "Kuzey Kore", dialCode: "850" },
  { iso2: "XK", name: "Kosova", dialCode: "383" },
  { iso2: "CR", name: "Kosta Rika", dialCode: "506" },
  { iso2: "CI", name: "Fildişi Sahili", dialCode: "225" },
  { iso2: "KW", name: "Kuveyt", dialCode: "965" },
  { iso2: "CV", name: "Yeşil Burun Adaları", dialCode: "238" },
  { iso2: "LA", name: "Laos", dialCode: "856" },
  { iso2: "LS", name: "Lesotho", dialCode: "266" },
  { iso2: "LV", name: "Letonya", dialCode: "371" },
  { iso2: "LR", name: "Liberya", dialCode: "231" },
  { iso2: "LY", name: "Libya", dialCode: "218" },
  { iso2: "LI", name: "Lihtenştayn", dialCode: "423" },
  { iso2: "LT", name: "Litvanya", dialCode: "370" },
  { iso2: "LB", name: "Lübnan", dialCode: "961" },
  { iso2: "LU", name: "Lüksemburg", dialCode: "352" },
  { iso2: "HU", name: "Macaristan", dialCode: "36" },
  { iso2: "MG", name: "Madagaskar", dialCode: "261" },
  { iso2: "MO", name: "Makao", dialCode: "853" },
  { iso2: "MW", name: "Malavi", dialCode: "265" },
  { iso2: "MV", name: "Maldivler", dialCode: "960" },
  { iso2: "MY", name: "Malezya", dialCode: "60" },
  { iso2: "ML", name: "Mali", dialCode: "223" },
  { iso2: "MT", name: "Malta", dialCode: "356" },
  { iso2: "MA", name: "Fas", dialCode: "212" },
  { iso2: "MH", name: "Marshall Adaları", dialCode: "692" },
  { iso2: "MU", name: "Mauritius", dialCode: "230" },
  { iso2: "MR", name: "Moritanya", dialCode: "222" },
  { iso2: "MX", name: "Meksika", dialCode: "52" },
  { iso2: "MC", name: "Monako", dialCode: "377" },
  { iso2: "MN", name: "Moğolistan", dialCode: "976" },
  { iso2: "MZ", name: "Mozambik", dialCode: "258" },
  { iso2: "MD", name: "Moldova", dialCode: "373" },
  { iso2: "MM", name: "Myanmar", dialCode: "95" },
  { iso2: "NA", name: "Namibya", dialCode: "264" },
  { iso2: "NR", name: "Nauru", dialCode: "674" },
  { iso2: "NP", name: "Nepal", dialCode: "977" },
  { iso2: "NE", name: "Nijer", dialCode: "227" },
  { iso2: "NG", name: "Nijerya", dialCode: "234" },
  { iso2: "NI", name: "Nikaragua", dialCode: "505" },
  { iso2: "NO", name: "Norveç", dialCode: "47" },
  { iso2: "NZ", name: "Yeni Zelanda", dialCode: "64" },
  { iso2: "OM", name: "Umman", dialCode: "968" },
  { iso2: "RU", name: "Rusya", dialCode: "7" },
  { iso2: "PA", name: "Panama", dialCode: "507" },
  { iso2: "PG", name: "Papua Yeni Gine", dialCode: "675" },
  { iso2: "PY", name: "Paraguay", dialCode: "595" },
  { iso2: "PK", name: "Pakistan", dialCode: "92" },
  { iso2: "PW", name: "Palau", dialCode: "680" },
  { iso2: "PE", name: "Peru", dialCode: "51" },
  { iso2: "PL", name: "Polonya", dialCode: "48" },
  { iso2: "PT", name: "Portekiz", dialCode: "351" },
  { iso2: "RO", name: "Romanya", dialCode: "40" },
  { iso2: "RW", name: "Ruanda", dialCode: "250" },
  { iso2: "SN", name: "Senegal", dialCode: "221" },
  { iso2: "RS", name: "Sırbistan", dialCode: "381" },
  { iso2: "SC", name: "Seyşeller", dialCode: "248" },
  { iso2: "SL", name: "Sierra Leone", dialCode: "232" },
  { iso2: "SG", name: "Singapur", dialCode: "65" },
  { iso2: "SK", name: "Slovakya", dialCode: "421" },
  { iso2: "SI", name: "Slovenya", dialCode: "386" },
  { iso2: "SB", name: "Solomon Adaları", dialCode: "677" },
  { iso2: "SO", name: "Somali", dialCode: "252" },
  { iso2: "LK", name: "Sri Lanka", dialCode: "94" },
  { iso2: "SD", name: "Sudan", dialCode: "249" },
  { iso2: "SS", name: "Güney Sudan", dialCode: "211" },
  { iso2: "SR", name: "Surinam", dialCode: "597" },
  { iso2: "SY", name: "Suriye", dialCode: "963" },
  { iso2: "SA", name: "Suudi Arabistan", dialCode: "966" },
  { iso2: "SZ", name: "Esvatini", dialCode: "268" },
  { iso2: "TJ", name: "Tacikistan", dialCode: "992" },
  { iso2: "TZ", name: "Tanzanya", dialCode: "255" },
  { iso2: "TH", name: "Tayland", dialCode: "66" },
  { iso2: "TW", name: "Tayvan", dialCode: "886" },
  { iso2: "TG", name: "Togo", dialCode: "228" },
  { iso2: "TO", name: "Tonga", dialCode: "676" },
  { iso2: "TT", name: "Trinidad ve Tobago", dialCode: "1868" },
  { iso2: "TN", name: "Tunus", dialCode: "216" },
  { iso2: "TR", name: "Türkiye", dialCode: "90" },
  { iso2: "TM", name: "Türkmenistan", dialCode: "993" },
  { iso2: "TV", name: "Tuvalu", dialCode: "688" },
  { iso2: "UG", name: "Uganda", dialCode: "256" },
  { iso2: "UA", name: "Ukrayna", dialCode: "380" },
  { iso2: "AE", name: "Birleşik Arap Emirlikleri", dialCode: "971" },
  { iso2: "GB", name: "Birleşik Krallık", dialCode: "44" },
  { iso2: "US", name: "Amerika Birleşik Devletleri", dialCode: "1" },
  { iso2: "UY", name: "Uruguay", dialCode: "598" },
  { iso2: "UZ", name: "Özbekistan", dialCode: "998" },
  { iso2: "VU", name: "Vanuatu", dialCode: "678" },
  { iso2: "VA", name: "Vatikan", dialCode: "379" },
  { iso2: "VE", name: "Venezuela", dialCode: "58" },
  { iso2: "VN", name: "Vietnam", dialCode: "84" },
  { iso2: "YE", name: "Yemen", dialCode: "967" },
  { iso2: "GR", name: "Yunanistan", dialCode: "30" },
];

export const COUNTRIES: CountryOption[] = [...RAW_COUNTRIES].sort((a, b) =>
  a.name.localeCompare(b.name, "tr")
);

export function flagEmoji(iso2: string): string {
  return iso2
    .toUpperCase()
    .split("")
    .map((c) => String.fromCodePoint(127397 + c.charCodeAt(0)))
    .join("");
}

// navigator.language (orn. "tr-TR") uzerinden ulke tahmini - ag
// istegi gerektirmeyen, tarayici tabanli en pratik "otomatik
// algilama" yontemi.
export function detectCountryFromLocale(): CountryOption | null {
  if (typeof navigator === "undefined") return null;
  const locale = navigator.language || (navigator as any).userLanguage;
  if (!locale) return null;
  const parts = locale.split("-");
  const region = parts[1]?.toUpperCase();
  if (!region) return null;
  return COUNTRIES.find((c) => c.iso2 === region) ?? null;
}
